frontend:
  phases:
    preBuild:
      commands:
        - nvm install 18
        - nvm use 18
        - node -v  # (Optional) to log the current version
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
